### ISSUE TITLE
Unable to use Param utilities unless backtester is connected

### ISSUE THREAD

**Issue by NickCrowe** [ConquerTheMarkets/ctm-backtester-cs-ui-issues-param-utils#4]
**Is your feature request related to a problem? Please describe.**

To use the Param Utilities functionality, the back tester needs to be running.

**Describe the solution you'd like**

You are able to use the website to do 'things' that do not require the back tester running (i.e. uploading / downloading parameter files). Only when you need to use the back tester you are prompted to run / start it.

**Describe alternatives you've considered**

No alternatives have been considered.

**Additional context**

You cannot get past this screen unless the back tester is running:

![image](https://github.com/user-attachments/assets/cdddc7dd-8abc-4384-8d2a-2f91f9d77844)

**Comment by romancerny** [comment]
Thank you for the question.

This is by design and will remain that way. The backtester abstracts away the cryptography behind Authorisation/Authentication and hosts all necessary data services.
